### ISSUE TITLE
Using Players As Optional Arguments In Commands

### ISSUE THREAD

**Issue by Vexaaah** [funkemunky/Atlas#5]
Im not sure if this is implemented I Asked Fozzie on discord and he said to make an issue on the github i am trying to make a command that i can use players optionally. If this isnt implemented can you implement it asap thanks

**Comment by funkemunky** [comment]
Sorry for being very late to response. I'm sure this issue may very well be resolved. However, you are not forced to use the CommandAdapter#getPlayer method. In the Command annotation, you can force it to be for players only by setting `@Command(player = true)`. Otherwise, just use CommandAdapter#getSender and that should fix your problem.

**Comment by funkemunky** [comment]
This is implemented.
